### ISSUE TITLE
Unable to run HighchartsPHP.. even demo .

### ISSUE THREAD

**Issue by marafis** [ghunti/HighchartsPHP#21]
hi
I am trying to run your demo .. I installed Using composer..... When I am about to run your Demo I am getting following error ...
Fatal error: Class 'Ghunti\HighchartsPHP\Highchart' not found in G:\xampp\htdocs\Phase3\phpHigh\vendor\ghunti\highcharts-php\demos\highcharts\area\area_range.php on line 5

**Comment by apurvtyagi** [comment]
Hi,
I am trying to run your demo .. I installed Using composer..... When I am about to run your Demo I am getting following error ...

PHP Fatal error:  Class 'Ghunti\HighchartsPHP\Highchart' not found in /var/www/html/HighchartsPHP/demos/highcharts/area/area_range.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/html/HighchartsPHP/demos/highcharts/area/area_range.php:0

**Comment by ghunti** [comment]
Hi @apurvtyagi you need to include the `autoload.php` file generated by composer that is under the `vendor` folder before you start using the HighchartsPHP classes https://getcomposer.org/doc/01-basic-usage.md#autoloading
