### ISSUE TITLE
PHP Fatal error:  Class 'Highchart' not found 

### ISSUE THREAD

**Issue by DeanKamali** [ghunti/HighchartsPHP#27]
Hey everyone, 

I have used composer to setup HighchartsPHP in my working directory, I have verified that the wrapper exists in vendor directory. 
`/var/www/php/system/sa/vendor/ghunti/highcharts-php`

I have created graph.php as  demo page and included the following

`<?php require 'vendor/autoload.php'; $chart = new Highchart();`

but I keep getting `PHP Fatal error:  Class 'Highchart' not found in /var/www/php/system/sa/graph.php`

I would appreciate if someone can help me with this, I'm looking forward to using this wrapper on my website.

**Comment by kazemisoroush** [comment]
+1

**Comment by joseammendola** [comment]
Sorry but it's work for me 

<?php
use Ghunti\HighchartsPHP\Highchart;
use Ghunti\HighchartsPHP\HighchartJsExpr;

//$chart = new Highchart();

$chart->includeExtraScripts();


the answer ==> 

( ! ) Fatal error: Class 'Ghunti\HighchartsPHP\Highchart' not found in C:\wamp\www\highphp\vendor\ghunti\highcharts-php\demos\highcharts\area\area_range.php on line 6
--
