### ISSUE TITLE
Change config.php to pull https:// instead of http://

### ISSUE THREAD

**Issue by bbrink68** [ghunti/HighchartsPHP#29]
I would love to see the default config.php reference `https://` assets instead of `http://`.  On any sites using SSL with a decently updated browser will have the scripts blocked.  Changing this to https:// should still allow non SSL sites to pull in the scripts.  Even omitting the protocol should be OK too, that should allow the browser to automatically add the proper protocol on.

Currently, I am needing to manually change these, and of course any `composer update` ran overwrites the changes.

**Comment by gqueiros** [comment]
Hi @bbrink68 
Can you please create a pull request?
Thanks

**Comment by bbrink68** [comment]
Done, thanks for your responsiveness on this!
