### ISSUE TITLE
Is heatmap supported ?

### ISSUE THREAD

**Issue by Pandahisham** [ghunti/HighchartsPHP#32]

**Comment by gqueiros** [comment]
Hi.
It should work, as long as it follows the same principles of other charts (a json object as the chart configuration).
Thanks

**Comment by ghunti** [comment]
Hi.
It should work, as long as it follows the same principles of other charts (a json object as the chart configuration).
Thanks

**Comment by Pandahisham** [comment]
yap , it does (Y)
