### ISSUE TITLE
Support for Highmaps

### ISSUE THREAD

**Issue by lurkie** [ghunti/HighchartsPHP#35]
I noticed that support for Highmaps is not yet included. For my project, I added some basic support for it, and I am willing to provide the patch to you.

**Comment by ghunti** [comment]
Hi @lurkie.

Can you provide the patch? I'm a bit swapped with work right now, but will look into it when I can ok?

Thanks

**Comment by lurkie** [comment]
Sure, please see https://github.com/ghunti/HighchartsPHP/pull/36

**Comment by jufy** [comment]
How to get it from composer?

**Comment by lurkie** [comment]
Probably by using something like dev-master, as it has not yet been released in a new version: https://getcomposer.org/doc/articles/aliases.md

**Comment by ghunti** [comment]
My bad. Will bump the version

**Comment by ghunti** [comment]
Done in https://github.com/ghunti/HighchartsPHP/tree/v3.0.3

Thanks
