### ISSUE TITLE
implementing a network graph in 

### ISSUE THREAD

**Issue by tesiag** [ghunti/HighchartsPHP#49]
This is not actually an issue but a request for suggestions  on how to implement in highchartsphp a "customized" network graph like that at the following link:
https://www.highcharts.com/demo/network-graph

Basically the question is how to code in highchartsphp the part relevant to the event addition as per js code below:
 
Highcharts.addEvent(
    Highcharts.seriesTypes.networkgraph,
    'afterSetOptions',
    function (e) {
        var colors = Highcharts.getOptions().colors,   i = 0,   nodes = {};
        e.options.data.forEach(function (link) {
            if (link[0] === 'Proto Indo-European') {
                nodes['Proto Indo-European'] = {
                    id: 'Proto Indo-European',
                    marker: { radius: 20 }
                };
                nodes[link[1]] = {
                    id: link[1],
                    marker: { radius: 10 },
                    color: colors[i++]
                };
            } 
           else if (nodes[link[0]] && nodes[link[0]].color) {
                nodes[link[1]] = {
                    id: link[1],
                    color: nodes[link[0]].color
                };
            }
        });
        e.options.nodes = Object.keys(nodes).map(function (id) { return nodes[id]; });
    }
);

Any hint or suggestion is warmly weòcome. Thank you
Andrea

**Comment by ghunti** [comment]
Hi @tesiag the wrapper doesn't support that :-(
