### ISSUE TITLE
PHP 7.4 and mixed makes error

### ISSUE THREAD

**Issue by lustmordtheblackpost** [ghunti/HighchartsPHP#56]
public function offsetGet($offset): mixed
    {
        if (!isset($this->_options[$offset])) {
            $this->_options[$offset] = new HighchartOption();
        }
        return $this->_options[$offset];
    }

**Comment by ghunti** [comment]
Hi @lustmordtheblackpost 
The latest version only supports PHP 8.0 +
Support for PHP 7.4 was only present until version 3.0.5
